services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.58.2-noble
    working_dir: /app
    container_name: playwright
    volumes:
      - .:/app
      - ./playwright-report:/app/playwright-report
    environment:
      - APP_ENV=local
      - PLAYWRIGHT_BASE_URL=https://faceapi.regulaforensics.com/
    command: /bin/sh -c 'npx playwright test --workers=1'
